== Besprechung 5.12.2018
:toc:

=== Ziel
.Ziel des Teams
Wir wollen durch effektives kollaboratives Zusammenarbeiten und Ausnutzung der gegebenen Ressource mit moderatem Zeitaufwand die SAT Challenge der Vorlesung Formale System gewinnen. Unser Vorteil gegenüber anderen Teams ist die strukturierte, organisierte und dadurch effiziente Arbeitsweise im Vergleich mit den anderen studentischen Teams.

.Persönlichen Ziele
Die persönlichen Ziele von Klaus, Markus, Richard und Georg stimmen mit dem Ziel des Teams überein

.Martins Ziel:
[quote, Martin Weih]
Mir persönlich ist es auch nicht so wichtig zu "gewinnen" oder gut abzuschneiden, ich möchte eher etwas an meiner programmierung arbeiten und finde das thema recht interessant.


=== Zeitaufwand
Jeder nennt seine Persönliche Vorstellungen, damit wir mit den gegebenen Ressourcen das bestmögliche Ergebnis erzielen können.

=== Verhaltenscodex
* Kollaboration ist unsere Stärke
** Entscheidungen sind bindend, d.h. sie werden unabhängig von der persönlichen Meinung umgesetzt
* Absolute Verlässlichkeit
** Lieber Aufgaben zurückweisen als durch Nichterfüllung Nachteile für die Teammitglieder zu erzuegen +
** Berechtigterweise merkt Klaus an, dass dies nicht in Form von harten Deadlines geschehen muss. Der Wortlaut wurde entsprechend angepasst.
* Dualismus von Kritik:
.. nur konstruktive, rationale Kritik ist zulässlich
.. Kritik ist eine Chance, kein Ärgernis
* Anerkennung von Verantwortlichkeit: Rechenschaft und Entscheidungshoheit
* Explizit ist besser als Implizit.
** Explizite Kommunikation ist besser als Implizite Kommunikation *Aber*: Was geklärt ist wird nicht wiederholt
** sämtlicher Code muss kommentiert und für jeden verständlich sein (Stichwort: Kollaboration)
*** Source Code Englisch, docs in Deutsch
** Abkürzungen, bei denen nicht sicher ist ob sie allen bekannt sind, sind nicht zu verwenden
* Jedes Feature muss durch einen *schriftlichen* Vorher/Nachher Vergleich bezüglich der Performance begründet werden. +
[quote, Donald Knuth, Paper:  "Structured Programming With Go To Statements"]
Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: *premature optimization is the root of all evil*. Yet we should not pass up our opportunities in that critical 3%.

** Kürze ist in Ordnung, die Existenz und Einsehbarkeit des Nachweis ist relevant

=== Technologie
.Solver
Resultat: Richard und Klaus haben sich über die Solver informiert, sie wollen abwarten bis der C Prototyp fertiggestellt ist.

.Programmiersprache
Es gab eine Diskussion ob Python oder C das Mittel der Wahl ist. Markus schreibt einen C Prototypen um die Performance mit Python zu vergleichen

.Wahl des Kommunikationsmittels
Einstimmig Slack

=== Konkrete Organisation

==== Zeitplan
Woche 1: Erarbeiten der Features +
Woche 2: Zusammenbringen und Feinschliff

==== Verantwortlichkeiten
Klaus erklärt sich verantwortlich, alle Informationen rund um die Anforderungen des Wettbewerbs sowie Tipps von den Tutoren zu sammeln und aufzubereiten. +
Richard und Georg sind verantworlich für die Recherche und Umsetzung der Constraints und des Präprozessors. +
Richard und Markus sind für die Codefusion im Repository verantwortlich. +
Georg übernimmt die Verantwortung für die Planung.

==== Aufgabenverteilung
|===
| Wer ist verantwortlich? | Was s | Bis einschließlich

| Markus | C Prototypen für den Performance Vergleich | 8.12
| Markus | automatisches Profiling | 9.12
| Markus | Privates Repository | 5.12
| Klaus | Auswahl des Solvers | 12.12
| Georg | Planung |
|===

==== offene Ideen
* Logikminimierer nachschauen


==== weitere Termine
Der nächste Termin ist am Sa, den 8.12.2018 in der 6. DS. Markus hat angeboten, dass wir uns in seiner WG treffen.

=== Fazit
Markus, Klaus und Georg äußern sich sehr zufrieden über die Zusammenarbeit und sehen gute Chancen, den Wettbewerb zu gewinnen.